_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.11.7
        t:
            "1":
                - 1
                - 9
                - 41
                - 55
                - 103
            "2":
                - 1
                - 9
                - 41
                - 55
                - 103
            "3":
                - 2
                - 23
                - 55
            "4": 3.11.7
            "5": 0.18.5
            "8":
                - 1
                - 3
                - 5
            "12": 0.18.5
            "13": windows-amd64
